volumes:
  acme:
  certs:
  html:
  node-data:

networks:
  node-network:
    internal: true
    ipam:
      config:
        - subnet: ${INTERNAL_NETWORK_SUBNET:?err_unset}
  inet:

services:
  node:
    image: zkverify/relay-node:${NODE_VERSION:?err_unset}
    container_name: "${NODE_ROLE:?err_unset}"
    restart: on-failure:5
    env_file:
      - .env
    environment:
      - "LETSENCRYPT_HOST=${ACME_VHOST:?err_unset}"
      - "VIRTUAL_HOST=${ACME_VHOST:?err_unset}"
      - "VIRTUAL_PORT=${NODE_NET_P2P_PORT_WS:?err_unset}"
    networks:
      node-network:
        ipv4_address: ${NODE_NET_IP_ADDRESS:?err_unset}
      inet:
    ports:
      - "${NODE_NET_P2P_PORT:?err_unset}:${NODE_NET_P2P_PORT:?err_unset}"
      - "${NODE_NET_P2P_PORT_WS:?err_unset}:${NODE_NET_P2P_PORT_WS:?err_unset}"
    volumes:
      - "node-data:/data:rw"
    logging:
      driver: "json-file"
      options:
        max-size: "512m"
        max-file: "4"

  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    pull_policy: always
    restart: on-failure:5
    depends_on:
      - node
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "certs:/etc/nginx/certs:ro"
      - "html:/usr/share/nginx/html:rw"
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
    environment:
      - DEBUG=true
      - TRUST_DOWNSTREAM_PROXY=true
    networks:
      node-network:
        ipv4_address: ${NGINX_NET_IP_ADDRESS:?err_unset}
      inet:
    tmpfs:
      - /var/cache/nginx
      - /run
    logging:
      driver: "json-file"
      options:
        max-size: "512m"
        max-file: "4"

  acme-companion:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    pull_policy: always
    restart: on-failure:5
    depends_on:
      - nginx-proxy
    environment:
      - "DEFAULT_EMAIL=${ACME_DEFAULT_EMAIL:?err_unset}"
      - NGINX_PROXY_CONTAINER=nginx-proxy
    volumes:
      - "acme:/etc/acme.sh:rw"
      - "certs:/etc/nginx/certs:rw"
      - "html:/usr/share/nginx/html:rw"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      inet:
    tmpfs:
      - /var/cache
      - /run
    logging:
      driver: "json-file"
      options:
        max-size: "512m"
        max-file: "4"
